QMAKE_DEPENDS_LIBJPEG16BITS_CC =
QMAKE_DEPENDS_LIBJPEG16BITS_LD =
QMAKE_INCDIR_LIBJPEG16BITS = 
QMAKE_DEFINES_LIBJPEG16BITS = 
QMAKE_LIBS_LIBJPEG16BITS =
QMAKE_LIBS_LIBJPEG16BITS_DEBUG = $$[QT_INSTALL_LIBS]/qtlibjpeg16bitsd.lib
QMAKE_LIBS_LIBJPEG16BITS_RELEASE = $$[QT_INSTALL_LIBS]/qtlibjpeg16bits.lib
