QMAKE_DEPENDS_LIBJPEG12BITS_CC =
QMAKE_DEPENDS_LIBJPEG12BITS_LD =
QMAKE_INCDIR_LIBJPEG12BITS = 
QMAKE_DEFINES_LIBJPEG12BITS = 
QMAKE_LIBS_LIBJPEG12BITS =
QMAKE_LIBS_LIBJPEG12BITS_DEBUG = $$[QT_INSTALL_LIBS]/qtlibjpeg12bitsd.lib
QMAKE_LIBS_LIBJPEG12BITS_RELEASE = $$[QT_INSTALL_LIBS]/qtlibjpeg12bits.lib
