QMAKE_DEPENDS_PCRE2_CC =
QMAKE_DEPENDS_PCRE2_LD =
QMAKE_INCDIR_PCRE2 = $$[QT_INSTALL_HEADERS]/qtpcre2
QMAKE_DEFINES_PCRE2 = PCRE2_CODE_UNIT_WIDTH=16 PCRE2_STATIC
QMAKE_LIBS_PCRE2 =
QMAKE_LIBS_PCRE2_DEBUG = $$[QT_INSTALL_LIBS]/qtpcre2d.lib
QMAKE_LIBS_PCRE2_RELEASE = $$[QT_INSTALL_LIBS]/qtpcre2.lib
