QT.network_private.VERSION = 5.15.19
QT.network_private.name = QtNetwork
QT.network_private.module =
QT.network_private.libs = $$QT_MODULE_LIB_BASE
QT.network_private.includes = $$QT_MODULE_INCLUDE_BASE/QtNetwork/5.15.19 $$QT_MODULE_INCLUDE_BASE/QtNetwork/5.15.19/QtNetwork
QT.network_private.frameworks =
QT.network_private.depends = core_private network
QT.network_private.uses = openssl
QT.network_private.module_config = v2 staticlib internal_module
QT.network_private.enabled_features = openssl-linked openssl netlistmgr system-proxies
QT.network_private.disabled_features = libproxy linux-netlink
QMAKE_INCDIR_OPENSSL = "C:\\Program Files\\OpenSSL/include"
QMAKE_LIBS_OPENSSL = "-LC:\\Program Files\\OpenSSL/lib" -lUser32 -lAdvapi32 -lGdi32 -lCrypt32 -lWs2_32
QMAKE_LIBS_OPENSSL_DEBUG = -llibcrypto64MTd -llibssl64MTd
QMAKE_LIBS_OPENSSL_RELEASE = -llibcrypto64MT -llibssl64MT
QMAKE_LIBS_NETWORK = ws2_32.lib
